#Buildr.settings.build['scala.version'] = "2.8.0.Beta1"
Buildr.settings.build['scala.version'] = "2.8.0"
require 'buildr/scala'

# Generated by Buildr 1.4.1, change to your liking
# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "trigonal"
COPYRIGHT = ""

LWJGL_URL='http://downloads.sourceforge.net/project/java-game-lib/Official%20Releases/LWJGL%202.5/lwjgl-2.5.zip'
LWJGL='org.lwjgl:lwjgl:jar:2.5'
LWJGL_UTIL='org.lwjgl:lwjgl-util:jar:2.5'
SCALA_LIB='org.scala-lang:scala-library:jar:2.8.0'
SPECS=[LWJGL, LWJGL_UTIL]

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"

desc "The Trigonal project"
define "trigonal" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
  compile.with SPECS
  package(:jar)

  task :extract do
    lwjgl_zip=download('target/lwjgl-2.5.zip'=>LWJGL_URL)
    extracted=unzip('target/lwjgl-2.5'=>lwjgl_zip)
    extracted.from_path('lwjgl-2.5').include('jar/*')
    extracted.from_path('lwjgl-2.5').include('native/linux/*')
    extracted.target.invoke
  end

  lwjgl_jar=file('target/lwjgl-2.5/jar/lwjgl.jar'=>"extract")
  lwjgl=artifact(LWJGL).from(lwjgl_jar)

  lwjgl_util_jar=file('target/lwjgl-2.5/jar/lwjgl_util.jar'=>"extract")
  lwjgl_util=artifact(LWJGL_UTIL).from(lwjgl_util_jar)

  task :run => [compile, "extract"] do
    cp = Buildr.artifacts(SPECS+[SCALA_LIB]).each(&:invoke).map(&:name).join(File::PATH_SEPARATOR)
    lib="target/lwjgl-2.5/native/linux"
    cmd="java -cp target/classes:#{cp} -Djava.library.path=#{lib} App miku/miku01.mqo"
    p cmd
    system cmd
  end
end

